name: Build and (optionally) Push Backend Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Remove this step if you don't want to push to Docker Hub

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mirror_app_backend:latest .

      # Uncomment to push to Docker Hub
      #- name: Push Docker image
      #  run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mirror_app_backend:latest

      - name: Print success
        run: echo "Docker image built successfully!"

# To use this workflow:
# 1. Add your secrets (DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, SUPABASE_URL, etc.) in GitHub repo settings.
# 2. Uncomment the push step if you want to push to Docker Hub.
# 3. Adjust image name as needed. 